use std::collections::{BTreeMap, BTreeSet};

use async_trait::async_trait;
use buzz_sim_protocol::{canonical_json_bytes, sha256_hex};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::{NpcActionDraft, ValidatedNpcAction, ValidatedNpcTurn};

const MAX_ACTION_ID_BYTES: usize = 256;
const MAX_EXECUTOR_NAME_BYTES: usize = 128;
const MAX_EXECUTOR_REASON_BYTES: usize = 4096;
const MAX_EXTERNAL_REFERENCE_BYTES: usize = 2048;

/// Immutable, identity-bound command sent to an external NPC action executor.
///
/// This envelope does not authorize new behavior. It contains only an action that already passed
/// persona and disclosure policy in [`crate::NpcOrchestrator`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NpcActionCommand {
    /// Simulation session that owns the side effect.
    pub session_id: Uuid,
    /// Idempotent NPC turn that proposed the side effect.
    pub turn_id: Uuid,
    /// Stable NPC actor identifier.
    pub actor_id: String,
    /// Stable action identifier generated by the orchestrator.
    pub action_id: String,
    /// Zero-based action order within the turn.
    pub sequence: u16,
    /// Digest of the complete model input used to produce the action.
    pub input_digest: String,
    /// Digest of the raw structured model output.
    pub output_digest: String,
    /// Policy-approved but still externally uncommitted action.
    pub action: NpcActionDraft,
}

impl NpcActionCommand {
    fn from_validated(
        turn: &ValidatedNpcTurn,
        sequence: usize,
        action: &ValidatedNpcAction,
    ) -> Result<Self, NpcDispatchError> {
        let sequence = u16::try_from(sequence).map_err(|_| NpcDispatchError::SequenceOverflow)?;
        let command = Self {
            session_id: turn.session_id,
            turn_id: turn.turn_id,
            actor_id: turn.actor_id.clone(),
            action_id: action.action_id.clone(),
            sequence,
            input_digest: turn.input_digest.clone(),
            output_digest: turn.output_digest.clone(),
            action: action.action.clone(),
        };
        command.validate()?;
        Ok(command)
    }

    /// Returns a stable digest binding the complete command envelope and action payload.
    pub fn digest(&self) -> Result<String, NpcDispatchError> {
        let value = serde_json::to_value(self)
            .map_err(|error| NpcDispatchError::Serialization(error.to_string()))?;
        let bytes = canonical_json_bytes(&value)
            .map_err(|error| NpcDispatchError::Serialization(error.to_string()))?;
        Ok(sha256_hex(&bytes))
    }

    fn validate(&self) -> Result<(), NpcDispatchError> {
        if !bounded_nonempty(&self.action_id, MAX_ACTION_ID_BYTES) {
            return Err(NpcDispatchError::InvalidActionId {
                action_id: self.action_id.clone(),
            });
        }
        if !sha256_digest(&self.input_digest) {
            return Err(NpcDispatchError::InvalidTurnDigest {
                field: "input_digest",
            });
        }
        if !sha256_digest(&self.output_digest) {
            return Err(NpcDispatchError::InvalidTurnDigest {
                field: "output_digest",
            });
        }
        Ok(())
    }
}

/// Terminal status reported by an external action executor.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NpcActionReceiptStatus {
    /// The external side effect completed synchronously.
    Completed,
    /// The external system accepted asynchronous work and returned a stable reference.
    Accepted,
}

/// Bounded error returned by a concrete Buzz, GitHub, calendar, or verification executor.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("{executor} executor failed: {reason}")]
pub struct NpcActionExecutorError {
    executor: String,
    reason: String,
}

impl NpcActionExecutorError {
    /// Creates a bounded executor error suitable for audit logs.
    pub fn new(
        executor: impl Into<String>,
        reason: impl Into<String>,
    ) -> Result<Self, NpcDispatchError> {
        let executor = executor.into();
        let reason = reason.into();
        if !bounded_nonempty(&executor, MAX_EXECUTOR_NAME_BYTES) {
            return Err(NpcDispatchError::InvalidExecutorError {
                reason: "executor name must be non-empty and at most 128 bytes".to_string(),
            });
        }
        if !bounded_nonempty(&reason, MAX_EXECUTOR_REASON_BYTES) {
            return Err(NpcDispatchError::InvalidExecutorError {
                reason: "executor reason must be non-empty and at most 4096 bytes".to_string(),
            });
        }
        Ok(Self { executor, reason })
    }
}

/// Auditable result returned after an executor applies or accepts one action.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NpcActionReceipt {
    /// Action identifier copied exactly from the command.
    pub action_id: String,
    /// Synchronous completion or asynchronous acceptance.
    pub status: NpcActionReceiptStatus,
    /// Stable executor implementation name.
    pub executor: String,
    /// Optional opaque pull request, branch, message, meeting, or verification reference.
    pub external_reference: Option<String>,
    /// Optional SHA-256 digest of trusted execution evidence.
    pub evidence_digest: Option<String>,
}

impl NpcActionReceipt {
    /// Creates and validates one executor receipt.
    pub fn new(
        action_id: impl Into<String>,
        status: NpcActionReceiptStatus,
        executor: impl Into<String>,
        external_reference: Option<String>,
        evidence_digest: Option<String>,
    ) -> Result<Self, NpcActionExecutorError> {
        let receipt = Self {
            action_id: action_id.into(),
            status,
            executor: executor.into(),
            external_reference,
            evidence_digest,
        };
        receipt
            .validate()
            .map_err(|reason| NpcActionExecutorError {
                executor: "receipt".to_string(),
                reason,
            })?;
        Ok(receipt)
    }

    fn validate(&self) -> Result<(), String> {
        if !bounded_nonempty(&self.action_id, MAX_ACTION_ID_BYTES) {
            return Err("receipt action id must be non-empty and at most 256 bytes".to_string());
        }
        if !bounded_nonempty(&self.executor, MAX_EXECUTOR_NAME_BYTES) {
            return Err("receipt executor must be non-empty and at most 128 bytes".to_string());
        }
        if self
            .external_reference
            .as_ref()
            .is_some_and(|value| !bounded_nonempty(value, MAX_EXTERNAL_REFERENCE_BYTES))
        {
            return Err("external reference must be non-empty and at most 2048 bytes".to_string());
        }
        if self
            .evidence_digest
            .as_ref()
            .is_some_and(|value| !sha256_digest(value))
        {
            return Err("evidence digest must be a 64-character SHA-256 value".to_string());
        }
        Ok(())
    }
}

/// External side-effect boundary for policy-approved NPC actions.
#[async_trait]
pub trait NpcActionExecutor: Send + Sync {
    /// Applies or accepts exactly one immutable command and returns an auditable receipt.
    async fn execute(
        &self,
        command: &NpcActionCommand,
    ) -> Result<NpcActionReceipt, NpcActionExecutorError>;
}

#[derive(Debug, Clone)]
struct DispatchRecord {
    command_digest: String,
    receipt: NpcActionReceipt,
}

/// In-memory idempotency projection for already dispatched NPC actions.
///
/// A persistent sidecar can rebuild this ledger from authoritative dispatch events. The ledger does
/// not contain credentials or provider response bodies.
#[derive(Debug, Clone, Default)]
pub struct NpcActionDispatchLedger {
    records: BTreeMap<String, DispatchRecord>,
}

impl NpcActionDispatchLedger {
    /// Number of successfully recorded action receipts.
    #[must_use]
    pub fn len(&self) -> usize {
        self.records.len()
    }

    /// Whether no action receipts have been recorded.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.records.is_empty()
    }

    fn lookup(
        &self,
        command: &NpcActionCommand,
    ) -> Result<Option<NpcActionReceipt>, NpcDispatchError> {
        let Some(record) = self.records.get(&command.action_id) else {
            return Ok(None);
        };
        if record.command_digest != command.digest()? {
            return Err(NpcDispatchError::ActionReplayConflict {
                action_id: command.action_id.clone(),
            });
        }
        Ok(Some(record.receipt.clone()))
    }

    fn record(
        &mut self,
        command: &NpcActionCommand,
        receipt: NpcActionReceipt,
    ) -> Result<(), NpcDispatchError> {
        let command_digest = command.digest()?;
        match self.records.get(&command.action_id) {
            Some(existing) if existing.command_digest != command_digest => {
                Err(NpcDispatchError::ActionReplayConflict {
                    action_id: command.action_id.clone(),
                })
            }
            Some(existing) if existing.receipt != receipt => {
                Err(NpcDispatchError::ReceiptReplayConflict {
                    action_id: command.action_id.clone(),
                })
            }
            Some(_) => Ok(()),
            None => {
                self.records.insert(
                    command.action_id.clone(),
                    DispatchRecord {
                        command_digest,
                        receipt,
                    },
                );
                Ok(())
            }
        }
    }
}

/// Complete result from dispatching one validated NPC turn.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NpcActionDispatchResult {
    /// Simulation session copied from the validated turn.
    pub session_id: Uuid,
    /// Turn identifier copied from the validated turn.
    pub turn_id: Uuid,
    /// NPC actor identifier copied from the validated turn.
    pub actor_id: String,
    /// Receipts in the exact declared action order.
    pub receipts: Vec<NpcActionReceipt>,
    /// Number of receipts served from the idempotency ledger.
    pub replayed_actions: usize,
}

/// Orders validated actions, enforces idempotency, and fail-stops external execution.
#[derive(Debug, Clone)]
pub struct NpcActionDispatcher<E> {
    executor: E,
    ledger: NpcActionDispatchLedger,
}

impl<E> NpcActionDispatcher<E> {
    /// Creates a dispatcher with an empty idempotency ledger.
    #[must_use]
    pub fn new(executor: E) -> Self {
        Self {
            executor,
            ledger: NpcActionDispatchLedger::default(),
        }
    }

    /// Creates a dispatcher from a rebuilt idempotency projection.
    #[must_use]
    pub const fn with_ledger(executor: E, ledger: NpcActionDispatchLedger) -> Self {
        Self { executor, ledger }
    }

    /// Returns the current idempotency projection.
    #[must_use]
    pub const fn ledger(&self) -> &NpcActionDispatchLedger {
        &self.ledger
    }

    /// Returns the concrete executor.
    #[must_use]
    pub const fn executor(&self) -> &E {
        &self.executor
    }
}

impl<E> NpcActionDispatcher<E>
where
    E: NpcActionExecutor,
{
    /// Dispatches actions strictly in order and stops at the first failed or invalid receipt.
    ///
    /// All action IDs and existing ledger records are preflighted before the first new side effect.
    /// Successfully completed earlier actions remain cached when a later action fails, making retry
    /// deterministic without repeating those side effects.
    pub async fn dispatch(
        &mut self,
        turn: &ValidatedNpcTurn,
    ) -> Result<NpcActionDispatchResult, NpcDispatchError> {
        let mut action_ids = BTreeSet::new();
        let mut prepared = Vec::with_capacity(turn.actions.len());
        for (sequence, action) in turn.actions.iter().enumerate() {
            if !action_ids.insert(action.action_id.clone()) {
                return Err(NpcDispatchError::DuplicateActionId {
                    action_id: action.action_id.clone(),
                });
            }
            let command = NpcActionCommand::from_validated(turn, sequence, action)?;
            let cached = self.ledger.lookup(&command)?;
            prepared.push((command, cached));
        }

        let mut receipts = Vec::with_capacity(prepared.len());
        let mut replayed_actions = 0;
        for (command, cached) in prepared {
            if let Some(receipt) = cached {
                replayed_actions += 1;
                receipts.push(receipt);
                continue;
            }

            let receipt = self.executor.execute(&command).await.map_err(|error| {
                NpcDispatchError::ExecutorFailed {
                    action_id: command.action_id.clone(),
                    executor: error.executor,
                    reason: error.reason,
                }
            })?;
            if receipt.action_id != command.action_id {
                return Err(NpcDispatchError::ReceiptActionMismatch {
                    expected: command.action_id,
                    actual: receipt.action_id,
                });
            }
            receipt
                .validate()
                .map_err(|reason| NpcDispatchError::InvalidReceipt {
                    action_id: command.action_id.clone(),
                    reason,
                })?;
            self.ledger.record(&command, receipt.clone())?;
            receipts.push(receipt);
        }

        Ok(NpcActionDispatchResult {
            session_id: turn.session_id,
            turn_id: turn.turn_id,
            actor_id: turn.actor_id.clone(),
            receipts,
            replayed_actions,
        })
    }
}

/// Deterministic dispatcher rejection or external action failure.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum NpcDispatchError {
    /// A canonical command digest could not be produced.
    #[error("NPC action command serialization failed: {0}")]
    Serialization(String),
    /// A validated turn exceeded the command sequence representation.
    #[error("NPC action sequence exceeded u16")]
    SequenceOverflow,
    /// A stable action identifier was empty or oversized.
    #[error("invalid NPC action id {action_id:?}")]
    InvalidActionId {
        /// Invalid action identifier.
        action_id: String,
    },
    /// One of the orchestrator input/output digests was malformed.
    #[error("{field} must be a 64-character SHA-256 value")]
    InvalidTurnDigest {
        /// Malformed digest field.
        field: &'static str,
    },
    /// A turn reused one action identifier more than once.
    #[error("duplicate NPC action id {action_id:?} in one turn")]
    DuplicateActionId {
        /// Duplicate action identifier.
        action_id: String,
    },
    /// An existing action identifier was paired with a different command envelope.
    #[error("NPC action id {action_id:?} was replayed with different content")]
    ActionReplayConflict {
        /// Conflicting action identifier.
        action_id: String,
    },
    /// The same command was paired with a different receipt.
    #[error("NPC action id {action_id:?} produced a conflicting receipt")]
    ReceiptReplayConflict {
        /// Conflicting action identifier.
        action_id: String,
    },
    /// An executor returned a receipt for another action.
    #[error("executor receipt action mismatch: expected {expected:?}, got {actual:?}")]
    ReceiptActionMismatch {
        /// Command action identifier.
        expected: String,
        /// Receipt action identifier.
        actual: String,
    },
    /// An executor returned a malformed receipt.
    #[error("invalid receipt for NPC action {action_id:?}: {reason}")]
    InvalidReceipt {
        /// Action identifier.
        action_id: String,
        /// Stable validation reason.
        reason: String,
    },
    /// A concrete external executor failed before returning a valid receipt.
    #[error("NPC action {action_id:?} failed in {executor}: {reason}")]
    ExecutorFailed {
        /// Failed action identifier.
        action_id: String,
        /// Executor implementation name.
        executor: String,
        /// Bounded failure reason.
        reason: String,
    },
    /// An executor attempted to construct an unbounded error.
    #[error("invalid NPC executor error: {reason}")]
    InvalidExecutorError {
        /// Validation reason.
        reason: String,
    },
}

fn bounded_nonempty(value: &str, maximum_bytes: usize) -> bool {
    !value.trim().is_empty() && value.len() <= maximum_bytes && !value.contains('\0')
}

fn sha256_digest(value: &str) -> bool {
    value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_hexdigit())
}
